# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0002_remove_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='fblog.Tag', verbose_name='\u6807\u7b7e\u96c6\u5408'),
        ),
    ]
