# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-17 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0003_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='fk_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b50\u7c7b\u540d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('fk_cate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fblog.Category')),
            ],
        ),
    ]
