# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-17 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0005_auto_20170417_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fk_category',
            old_name='fk_cate_id',
            new_name='fk_cate',
        ),
    ]
